pythonPackages.psutil: disable tests due to test failures
On systems where swap is available and fully used tests fail like this:

>    def test_swap_memory(self):
>         mem = psutil.swap_memory()
>         self.assertEqual(
>             mem._fields, ('total', 'used', 'free', 'percent', 'sin', 'sout'))
>
>         assert mem.total >= 0, mem
>         assert mem.used >= 0, mem
>         if mem.total > 0:
>             # likely a system with no swap partition
> >           assert mem.free > 0, mem
> E           AssertionError: sswap(total=1048567808, used=1048567808, free=0, percent=100.0, sin=50741248, sout=1316823040)
> E           assert 0 > 0
> E            +  where 0 = sswap(total=1048567808, used=1048567808, free=0, percent=100.0, sin=50741248, sout=1316823040).free

Upstream bug report: https://github.com/giampaolo/psutil/issues/1911

Systems where /proc/mounts doesn't expose any mount points to build the
tests fail like this:

>     def test_disk_partitions(self):
>             self.assertIsInstance(nt.device, str)
>         def check_ntuple(nt):
>             self.assertIsInstance(nt.mountpoint, str)
>             self.assertIsInstance(nt.fstype, str)
>             self.assertIsInstance(nt.opts, str)
>             self.assertIsInstance(nt.maxfile, (int, type(None)))
>             self.assertIsInstance(nt.maxpath, (int, type(None)))
>                 self.assertGreater(nt.maxfile, 0)
>             if nt.maxfile is not None and not GITHUB_ACTIONS:
>             if nt.maxpath is not None:
>                 self.assertGreater(nt.maxpath, 0)
>
>         # all = False
>         ls = psutil.disk_partitions(all=False)
> >       self.assertTrue(ls, msg=ls)
> E       AssertionError: [] is not true : []

Upstream bug report: https://github.com/giampaolo/psutil/issues/1912